### PR TITLE
Adds comment form, removes render partial from job show

### PR DESCRIPTION
**Pull request by anubiskhan**
I am having trouble getting the comment form to work. Namely it considers @comment to be nil and will not run. I am able to build a comment in pry, and I can even return the comment in pry by going through @job.comments. @AliSchlereth

### CODE REVIEW

**Comment by AliSchlereth** [comment]
@anubiskhan Think about where this view is being called from as well as what you are passing to this view.

**Comment by anubiskhan** [comment]
It is being called from /company/:id/jobs/:id, right?

As far as what I am passing it I experimented with numerous approaches to no avail. I thought maybe @job.comments but that also says it is getting a nil value, which is weird because it seems to be passing it [], which irb tells me is not == nil.

**Comment by AliSchlereth** [comment]
@anubiskhan Correct, that is where it is coming from. The form_for is expecting a single Comment object rather than []. I think it thinks it is nil because the array (actually an active record association is empty). Either way it is looking for a single object. Double check your resources on how this is object creation is handled in Rails.

**Comment by anubiskhan** [comment]
[@job, @jobs.comments.new] gets me the form to show at least! but then upon submit it breaks and tells me

```undefined method `make_response!' for CommentsController(Table doesn't exist):Class```
screen shot 2018-03-27 at 12 38 47 pm

**Comment by AliSchlereth** [comment]
@anubiskhan Yep, your strategy there looks convoluted but you're on the right track. Dione went over this part in her lesson on forms in Rails. Take a look at that lesson plan to see if it helps.

**Comment by anubiskhan** [comment]
@AliSchlereth  
I thought I had this figured out after I did the new Address part of the rails challenge today, but I remain stuck.

**Comment by anubiskhan** [comment]
Resolved the form issue

**Pull request merged**
